import * as fs from 'fs';
import * as path from 'path';
import { createClient } from '@supabase/supabase-js';
import sharp from 'sharp';
import dotenv from 'dotenv';
import { v4 as uuidv4 } from 'uuid'; // need uuid for primary keys

dotenv.config({ path: path.join(__dirname, '../../admin/.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseKey) {
  console.error("Missing Supabase credentials in admin/.env.local");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const BUCKET_NAME = 'products';
const BASE_URL = 'https://giftkyade.com/products.json?limit=250';
const SEED_FILE = path.join(__dirname, '../../seed_products.sql');

async function downloadAndCompressImage(url: string, filename: string): Promise<Buffer | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`Failed to fetch image: ${response.statusText}`);
    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    const compressed = await sharp(buffer)
      .resize({ width: 1200, withoutEnlargement: true })
      .webp({ quality: 65, effort: 6 }) 
      .toBuffer();

    return compressed;
  } catch (err) {
    console.error(`Error processing image ${url}:`, err);
    return null;
  }
}

function escapeSql(str: string): string {
  if (!str) return "''";
  return "'" + str.replace(/'/g, "''") + "'";
}

async function scrape() {
  console.log("🚀 Starting GiftKyaDe Scraper to SEED.SQL...");

  // Write header to seed file
  fs.writeFileSync(SEED_FILE, "-- Seed file generated by scraper\n\n");

  const { data: buckets } = await supabase.storage.listBuckets();
  if (!buckets?.find(b => b.name === BUCKET_NAME)) {
    console.log(`Creating bucket '${BUCKET_NAME}'...`);
    await supabase.storage.createBucket(BUCKET_NAME, { public: true });
  }

  let page = 1;
  let totalProducts = 0;
  let hasMore = true;

  const categoryMap = new Map<string, string>(); // name -> uuid

  while (hasMore) {
    const url = `${BASE_URL}&page=${page}`;
    console.log(`\nFetching page ${page}: ${url}`);
    
    const res = await fetch(url);
    if (!res.ok) {
      console.error(`Failed to fetch page ${page}: ${res.statusText}`);
      break;
    }

    const json = await res.json();
    const products = json.products;

    if (!products || products.length === 0) {
      console.log("No more products found.");
      hasMore = false;
      break;
    }

    console.log(`Found ${products.length} products on page ${page}. Processing...`);

    for (const item of products) {
      console.log(`-> Processing: ${item.title}`);
      
      const productType = item.product_type?.trim() || 'Uncategorized';
      let categoryId = categoryMap.get(productType);
      
      if (!categoryId) {
        categoryId = uuidv4();
        categoryMap.set(productType, categoryId);
        
        const slug = productType.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
        const catSql = `INSERT INTO public.categories (id, name, slug, description, is_active) VALUES ('${categoryId}', ${escapeSql(productType)}, ${escapeSql(slug)}, ${escapeSql('Collection of ' + productType)}, true) ON CONFLICT (slug) DO NOTHING;\n`;
        fs.appendFileSync(SEED_FILE, catSql);
      }

      const imageUrls: string[] = [];
      const imagesToProcess = (item.images || []).slice(0, 5);
      
      for (let i = 0; i < imagesToProcess.length; i++) {
        const img = imagesToProcess[i];
        const src = img.src;
        if (!src) continue;

        const ext = 'webp';
        const filename = `${item.handle}-${i}-${Date.now()}.${ext}`;

        const compressedBuffer = await downloadAndCompressImage(src, filename);
        if (compressedBuffer) {
          const { error: uploadError } = await supabase.storage
            .from(BUCKET_NAME)
            .upload(filename, compressedBuffer, {
              contentType: 'image/webp',
              upsert: true
            });
          
          if (!uploadError) {
            const { data: publicUrlData } = supabase.storage.from(BUCKET_NAME).getPublicUrl(filename);
            imageUrls.push(publicUrlData.publicUrl);
            console.log(`   [✓] Image ${i+1}/${imagesToProcess.length} uploaded (${Math.round(compressedBuffer.length/1024)} KB)`);
          } else {
            console.error(`   [x] Upload failed:`, uploadError);
          }
        }
      }

      let basePrice = 0;
      let compareAtPrice = null;
      if (item.variants && item.variants.length > 0) {
        basePrice = parseFloat(item.variants[0].price || "0");
        if (item.variants[0].compare_at_price) {
          compareAtPrice = parseFloat(item.variants[0].compare_at_price);
        }
      }

      const productId = uuidv4();
      const imagesArraySql = imageUrls.length > 0 
        ? `ARRAY[${imageUrls.map(url => escapeSql(url)).join(', ')}]::text[]` 
        : `ARRAY[]::text[]`;
      const description = escapeSql(item.body_html || item.title);
      const isBestseller = item.tags?.includes('bestseller') ? 'true' : 'false';

      const prodSql = `INSERT INTO public.products (id, title, slug, description, base_price, compare_at_price, images, category_id, is_active, is_bestseller) VALUES ('${productId}', ${escapeSql(item.title)}, ${escapeSql(item.handle)}, ${description}, ${basePrice}, ${compareAtPrice === null ? 'NULL' : compareAtPrice}, ${imagesArraySql}, '${categoryId}', true, ${isBestseller}) ON CONFLICT (slug) DO NOTHING;\n`;
      fs.appendFileSync(SEED_FILE, prodSql);

      if (item.variants && item.variants.length > 0) {
        for (const variant of item.variants) {
          const variantId = uuidv4();
          const vPrice = parseFloat(variant.price || "0");
          const vCompare = variant.compare_at_price ? parseFloat(variant.compare_at_price) : 'NULL';
          const sku = escapeSql(variant.sku || `${item.handle}-${variant.title}`);
          const stock = variant.inventory_quantity || 100;
          
          const varSql = `INSERT INTO public.product_variants (id, product_id, title, sku, price, compare_at_price, stock) VALUES ('${variantId}', '${productId}', ${escapeSql(variant.title)}, ${sku}, ${vPrice}, ${vCompare}, ${stock});\n`;
          fs.appendFileSync(SEED_FILE, varSql);
        }
        console.log(`   [✓] ${item.variants.length} variants processed.`);
      }

      totalProducts++;
    }

    page++;
    await new Promise(r => setTimeout(r, 1000));
  }

  console.log(`\n🎉 Scraping Complete! Total products processed: ${totalProducts}`);
  console.log(`\n📄 Generated seed.sql at ${SEED_FILE}`);
}

scrape().catch(err => {
  console.error("Scraper failed:", err);
});
